region                                  = "us-east-1"
env                                     = "dev"
key_name                                = "testkey"
image                                   = "ami-0022f774911c1d690"
instance_type                           = "t2.micro"