env                   = "dev"
iam_role_name         = "my-iam-eks-role"
aws_eks_cluster_name  = "my-eks-cluster"
node_group_name       = "my-node-group"
instance_profile_name = "my-eks-instance-profile"