variable "scenario" {}
variable "elasticip_name" {}
variable "nat_gateway_name" {}
variable "vpc_rtb_cidr_block" {}
variable "env" {}
variable "az" {}
variable "az1" {}
variable "test_tgw_id" {}
variable "vpc_sub_1" {}
variable "map_public_ip_on_launch" {}
variable "vpc_sub_2" {}
variable "cidr_block" {}
variable "map_public_ip_on_launch_1" {}
variable "ig_name" {}
variable "vpc_sub_1_cidr" {}
variable "vpc_sub_2_cidr" {}
variable "bucket_name" {}
