variable "resourcename" {}
variable "clustername" {}
variable "location" {}
variable "dnspreffix" {}
variable "size" {}
variable "agentnode" {}
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}