variable "vpc_id" {}
variable "image" {}
variable "key_name" {}
variable "security_group_vpc_name" {}
variable "env" {}
variable "instance_type" {}
variable "vpc_sub_1" {}
variable "vpc_sub_2" {}
variable "az" {}
variable "az1" {}
variable "scenario" {}
variable "vpc_1_2_3_sub_a" {}
variable "vpc_1_2_3_sub_b" {}